---
title: "Omics Data Analysis in R"
subtitle: "A textbook for my wife"
author: "Tu Hu"
date: "last updated on `r Sys.time()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: tuhulab/omics_analysis_r
description: "Omics data analysis in R"
---

# Introduction

## Motivation

I am writing this book to teach my wife how to analyze omics data using R. The reason for a new book is because, omics data analysis requires a wide range of knowledge and skills, including biology, omics, statistics, bioinformatics, and programming etc. These knowledge spreads in many textbooks, websites, and blogs. For a biologist without prior knowledge or exposure to these topics, such as my wife who graduates her master in biomedicine, the learning curve could be very steady if without guidance.

I decide first to start this book as teaching notes, documenting my teaching materials each day. Then, I plan to consolidate them into separate themes: R programming, biology, bioinformatics etc.

I assume the audience has (or is studying for) a bachelor degree in science. Therefore, the book starts from very basics.

## Acknowledgement

I thank my wife (and student) Jingyao who is always challenging herself.

When I write this book, I shamelessly "borrowed" a lot of contents from @holmes2018modern, @akalin2020.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
